-- Curriculum seed: makes the A1 -> C2 learning path reachable on a fresh install.
-- Adds lesson ordering, then seeds the curriculum spine (lessons), core vocabulary,
-- grammar rules, conversation templates and pronunciation exercises.
-- Lesson sections/exercises are intentionally NOT seeded: the app generates and
-- persists them with AI the first time a lesson is opened.
--
-- Topic conventions (coupled to src/lib/curriculum.ts):
--   'exam'        -> the lesson is a level checkpoint (learning-path gating) and
--                    surfaces as an exam module in /api/exam/modules
--   'tcf' / 'tef' -> exam flavor used to classify exam modules

-- 1. Lesson ordering ---------------------------------------------------------

ALTER TABLE public.lessons ADD COLUMN IF NOT EXISTS order_index INTEGER DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_lessons_level_order ON public.lessons(level, order_index);

-- 2. Lessons (curriculum spine, 12 per level) --------------------------------

INSERT INTO public.lessons (title, description, level, duration, topics, order_index) VALUES
-- A1
($$Bonjour ! Greetings and introductions$$, $$Say hello, introduce yourself and ask someone's name with basic polite phrases.$$, 'A1', 15, ARRAY['conversation','vocabulary','speaking'], 1),
($$The French alphabet and pronunciation basics$$, $$Learn the alphabet, accents and the core sounds of French.$$, 'A1', 15, ARRAY['pronunciation','listening'], 2),
($$Numbers, dates and telling time$$, $$Count, give the date and tell the time in everyday situations.$$, 'A1', 20, ARRAY['vocabulary','listening'], 3),
($$Articles and gender: le, la, un, une$$, $$Understand noun gender and choose the right definite or indefinite article.$$, 'A1', 20, ARRAY['grammar'], 4),
($$Être and avoir: your first verbs$$, $$Conjugate and use the two most important French verbs in the present tense.$$, 'A1', 20, ARRAY['grammar','conjugation'], 5),
($$Family and descriptions$$, $$Talk about your family and describe people with common adjectives.$$, 'A1', 20, ARRAY['vocabulary','reading'], 6),
($$Regular -er verbs in the present$$, $$Master the largest French verb group and talk about what you do.$$, 'A1', 20, ARRAY['grammar','conjugation'], 7),
($$Food and drink: at the café$$, $$Order food and drinks and understand a simple menu.$$, 'A1', 20, ARRAY['vocabulary','conversation','listening'], 8),
($$Asking questions: est-ce que, qui, où$$, $$Form simple questions to get the information you need.$$, 'A1', 20, ARRAY['grammar','conversation'], 9),
($$My daily routine$$, $$Describe your day using reflexive verbs and time expressions.$$, 'A1', 20, ARRAY['vocabulary','writing','reading'], 10),
($$Places in town and directions$$, $$Name places in a city and ask for or give simple directions.$$, 'A1', 20, ARRAY['vocabulary','listening','conversation'], 11),
($$A1 checkpoint: review and mini-exam$$, $$Consolidate everything from A1 with a graded review in exam format.$$, 'A1', 30, ARRAY['exam','tcf','reading','listening'], 12),
-- A2
($$Passé composé with avoir$$, $$Talk about completed past actions using avoir and past participles.$$, 'A2', 20, ARRAY['grammar','conjugation'], 1),
($$Passé composé with être$$, $$Use être verbs and agreement rules to narrate past movements and events.$$, 'A2', 20, ARRAY['grammar','conjugation'], 2),
($$Shopping and clothes$$, $$Buy clothes, discuss sizes and prices, and express preferences.$$, 'A2', 20, ARRAY['vocabulary','conversation'], 3),
($$L'imparfait: describing the past$$, $$Describe habits, feelings and background scenes in the past.$$, 'A2', 20, ARRAY['grammar'], 4),
($$Travel and transport$$, $$Buy tickets, understand announcements and manage travel situations.$$, 'A2', 20, ARRAY['vocabulary','listening','conversation'], 5),
($$Futur proche and futur simple$$, $$Make plans and predictions with both future forms.$$, 'A2', 20, ARRAY['grammar','conjugation'], 6),
($$Health and the body: chez le médecin$$, $$Explain symptoms and understand advice at the doctor's office.$$, 'A2', 20, ARRAY['vocabulary','conversation','listening'], 7),
($$Object pronouns: COD and COI$$, $$Replace nouns with le, la, les, lui and leur to sound natural.$$, 'A2', 25, ARRAY['grammar'], 8),
($$Writing informal letters and messages$$, $$Write short friendly emails, invitations and replies.$$, 'A2', 25, ARRAY['writing'], 9),
($$Weather, seasons and making plans$$, $$Discuss the weather and arrange activities with friends.$$, 'A2', 15, ARRAY['vocabulary','conversation'], 10),
($$Comparatives and superlatives$$, $$Compare people, places and things: plus, moins, aussi, le meilleur.$$, 'A2', 20, ARRAY['grammar'], 11),
($$A2 checkpoint: review and mini-exam$$, $$Consolidate everything from A2 with a graded review in exam format.$$, 'A2', 30, ARRAY['exam','tef','reading','listening'], 12),
-- B1
($$Le subjonctif présent: introduction$$, $$Recognize and form the subjunctive after il faut que, vouloir que and emotions.$$, 'B1', 25, ARRAY['grammar'], 1),
($$Expressing opinions and agreement$$, $$Give, support and challenge opinions in a discussion.$$, 'B1', 20, ARRAY['conversation','speaking','vocabulary'], 2),
($$Work and professional life$$, $$Describe jobs, workplaces and career plans; read simple job ads.$$, 'B1', 25, ARRAY['vocabulary','reading','writing'], 3),
($$Relative pronouns: qui, que, dont, où$$, $$Combine sentences smoothly with relative clauses.$$, 'B1', 25, ARRAY['grammar'], 4),
($$Media and current events$$, $$Understand headlines and short news reports and react to them.$$, 'B1', 25, ARRAY['reading','listening','vocabulary'], 5),
($$The conditional: politeness and hypotheses$$, $$Make polite requests and imagine hypothetical situations.$$, 'B1', 20, ARRAY['grammar','conjugation'], 6),
($$Narrating in the past: passé composé vs imparfait$$, $$Choose the right past tense to tell clear, vivid stories.$$, 'B1', 25, ARRAY['grammar','writing'], 7),
($$Environment and society$$, $$Discuss ecological and social topics with appropriate vocabulary.$$, 'B1', 25, ARRAY['vocabulary','reading','conversation'], 8),
($$Formal correspondence$$, $$Write formal letters and emails with the right openings and closings.$$, 'B1', 25, ARRAY['writing'], 9),
($$French culture and traditions$$, $$Explore holidays, gastronomy and customs across the francophone world.$$, 'B1', 20, ARRAY['reading','listening','culture'], 10),
($$Reported speech$$, $$Report what someone said with correct tense shifts.$$, 'B1', 25, ARRAY['grammar'], 11),
($$B1 checkpoint: TCF/TEF practice$$, $$A timed, exam-style review of the whole B1 programme.$$, 'B1', 40, ARRAY['exam','tcf','reading','listening','writing'], 12),
-- B2
($$Advanced subjunctive vs indicative$$, $$Choose the right mood after conjunctions, doubt and opinion verbs.$$, 'B2', 25, ARRAY['grammar'], 1),
($$Argumentation: structuring a debate$$, $$Build and defend a structured argument with connectors.$$, 'B2', 25, ARRAY['speaking','writing','conversation'], 2),
($$Abstract vocabulary: ideas and concepts$$, $$Discuss abstract themes such as freedom, progress and identity.$$, 'B2', 25, ARRAY['vocabulary','reading'], 3),
($$Passive voice and nominalization$$, $$Use passive constructions and noun forms typical of formal French.$$, 'B2', 25, ARRAY['grammar','writing'], 4),
($$Reading literature: short excerpts$$, $$Read and interpret accessible literary passages.$$, 'B2', 30, ARRAY['reading','culture'], 5),
($$Hypotheses with si clauses$$, $$Master si + imparfait / plus-que-parfait and their consequences.$$, 'B2', 25, ARRAY['grammar'], 6),
($$Professional emails and reports$$, $$Write clear workplace emails, summaries and short reports.$$, 'B2', 30, ARRAY['writing'], 7),
($$Understanding fast native speech$$, $$Train your ear on natural-speed dialogues, elisions and fillers.$$, 'B2', 25, ARRAY['listening','pronunciation'], 8),
($$Connectors and discourse markers$$, $$Link ideas elegantly: cependant, en revanche, par ailleurs, or donc.$$, 'B2', 20, ARRAY['grammar','writing','vocabulary'], 9),
($$Politics and institutions in France$$, $$Understand how French institutions work and the vocabulary of civic life.$$, 'B2', 25, ARRAY['vocabulary','reading','culture'], 10),
($$Expressing nuance: concession and opposition$$, $$Qualify statements with bien que, malgré, quoique and pourtant.$$, 'B2', 25, ARRAY['grammar','conversation'], 11),
($$B2 checkpoint: TCF/TEF practice$$, $$A timed, exam-style review of the whole B2 programme.$$, 'B2', 45, ARRAY['exam','tef','reading','listening','writing'], 12),
-- C1
($$Registers of French: formal, standard, familiar$$, $$Switch appropriately between soutenu, courant and familier.$$, 'C1', 25, ARRAY['vocabulary','conversation','culture'], 1),
($$Literary tenses: passé simple and beyond$$, $$Recognize and interpret literary tenses in written texts.$$, 'C1', 30, ARRAY['grammar','reading'], 2),
($$Essay writing: thèse, antithèse, synthèse$$, $$Write a classic structured French essay with a strong problématique.$$, 'C1', 40, ARRAY['writing'], 3),
($$Idiomatic expressions and figures of speech$$, $$Use common idioms and imagery the way natives do.$$, 'C1', 25, ARRAY['vocabulary','conversation'], 4),
($$Analyzing press articles$$, $$Dissect argumentation, tone and bias in the French press.$$, 'C1', 30, ARRAY['reading','vocabulary'], 5),
($$Debating complex issues$$, $$Hold your own in fast, nuanced debates on society and ethics.$$, 'C1', 30, ARRAY['speaking','conversation','listening'], 6),
($$Stylistics: elegance and precision$$, $$Refine sentence rhythm, word choice and cohesion in your writing.$$, 'C1', 30, ARRAY['writing','grammar'], 7),
($$French cinema and the arts$$, $$Discuss films and works of art with critical vocabulary.$$, 'C1', 25, ARRAY['listening','culture','vocabulary'], 8),
($$Advanced pronunciation: liaison, enchaînement, intonation$$, $$Perfect the melodic details that make speech sound native.$$, 'C1', 25, ARRAY['pronunciation','listening'], 9),
($$Academic and professional presentations$$, $$Structure and deliver polished presentations with confidence.$$, 'C1', 30, ARRAY['speaking','writing'], 10),
($$Regional French and the francophonie$$, $$Explore accents and variants from Québec, Belgium, Switzerland and Africa.$$, 'C1', 25, ARRAY['listening','culture','vocabulary'], 11),
($$C1 checkpoint: full exam simulation$$, $$A complete timed simulation covering all exam sections.$$, 'C1', 60, ARRAY['exam','tcf','reading','listening','writing','speaking'], 12),
-- C2
($$Mastering nuance: implicit meaning and irony$$, $$Detect subtext, irony and implication in sophisticated French.$$, 'C2', 30, ARRAY['reading','listening','vocabulary'], 1),
($$Literary analysis and critique$$, $$Analyze style, themes and structure in literary works.$$, 'C2', 40, ARRAY['reading','writing','culture'], 2),
($$Persuasion and rhetoric$$, $$Deploy classical rhetorical techniques in speech and writing.$$, 'C2', 30, ARRAY['speaking','writing'], 3),
($$Translating idiomatic French$$, $$Move between French and English without losing nuance.$$, 'C2', 30, ARRAY['vocabulary','grammar','writing'], 4),
($$Specialized domains: law, science, economics$$, $$Read and discuss specialized texts with domain vocabulary.$$, 'C2', 35, ARRAY['vocabulary','reading'], 5),
($$Humor, wordplay and puns$$, $$Understand and produce jeux de mots, double meanings and cultural humor.$$, 'C2', 25, ARRAY['vocabulary','listening','culture'], 6),
($$Perfecting written style$$, $$Eliminate the last anglicisms and polish register, rhythm and precision.$$, 'C2', 35, ARRAY['writing','grammar'], 7),
($$Simultaneous listening and note-taking$$, $$Take structured notes from lectures and debates in real time.$$, 'C2', 30, ARRAY['listening','writing'], 8),
($$Public speaking at native level$$, $$Deliver speeches with native-like fluency, pacing and presence.$$, 'C2', 30, ARRAY['speaking','pronunciation'], 9),
($$Contemporary French society: deep dive$$, $$Debate current social questions with full cultural context.$$, 'C2', 30, ARRAY['reading','culture','conversation'], 10),
($$Polishing: common advanced errors$$, $$Hunt down the subtle mistakes that persist at the highest level.$$, 'C2', 30, ARRAY['grammar','writing'], 11),
($$C2 checkpoint: full exam simulation$$, $$A complete timed simulation at mastery level.$$, 'C2', 60, ARRAY['exam','tef','reading','listening','writing','speaking'], 12);

-- 3. Vocabulary --------------------------------------------------------------

INSERT INTO public.vocabulary (french, english, example, level, category, pronunciation, usage_context) VALUES
-- A1
($$bonjour$$, $$hello / good morning$$, $$Bonjour, comment allez-vous ?$$, 'A1', 'greetings', $$bɔ̃.ʒuʁ$$, ARRAY['everyday','polite']),
($$merci$$, $$thank you$$, $$Merci beaucoup pour votre aide.$$, 'A1', 'greetings', $$mɛʁ.si$$, ARRAY['everyday','polite']),
($$s'il vous plaît$$, $$please (formal)$$, $$Un café, s'il vous plaît.$$, 'A1', 'greetings', $$sil vu plɛ$$, ARRAY['everyday','polite']),
($$au revoir$$, $$goodbye$$, $$Au revoir, à demain !$$, 'A1', 'greetings', $$o ʁə.vwaʁ$$, ARRAY['everyday']),
($$oui$$, $$yes$$, $$Oui, je comprends.$$, 'A1', 'basics', $$wi$$, ARRAY['everyday']),
($$non$$, $$no$$, $$Non, merci.$$, 'A1', 'basics', $$nɔ̃$$, ARRAY['everyday']),
($$la maison$$, $$house, home$$, $$Je rentre à la maison.$$, 'A1', 'home', $$mɛ.zɔ̃$$, ARRAY['everyday']),
($$l'école$$, $$school$$, $$Les enfants vont à l'école.$$, 'A1', 'education', $$e.kɔl$$, ARRAY['everyday']),
($$le pain$$, $$bread$$, $$J'achète le pain à la boulangerie.$$, 'A1', 'food', $$pɛ̃$$, ARRAY['food','shopping']),
($$l'eau$$, $$water$$, $$Je voudrais un verre d'eau.$$, 'A1', 'food', $$o$$, ARRAY['food']),
($$manger$$, $$to eat$$, $$Nous mangeons à midi.$$, 'A1', 'verbs', $$mɑ̃.ʒe$$, ARRAY['food','everyday']),
($$boire$$, $$to drink$$, $$Tu bois du café le matin ?$$, 'A1', 'verbs', $$bwaʁ$$, ARRAY['food','everyday']),
($$parler$$, $$to speak$$, $$Je parle un peu français.$$, 'A1', 'verbs', $$paʁ.le$$, ARRAY['everyday']),
($$habiter$$, $$to live (somewhere)$$, $$J'habite à Montréal.$$, 'A1', 'verbs', $$a.bi.te$$, ARRAY['everyday']),
($$la famille$$, $$family$$, $$Ma famille est grande.$$, 'A1', 'family', $$fa.mij$$, ARRAY['family']),
($$la mère$$, $$mother$$, $$Ma mère s'appelle Anne.$$, 'A1', 'family', $$mɛʁ$$, ARRAY['family']),
($$le père$$, $$father$$, $$Mon père travaille beaucoup.$$, 'A1', 'family', $$pɛʁ$$, ARRAY['family']),
($$le travail$$, $$work, job$$, $$Je vais au travail en bus.$$, 'A1', 'work', $$tʁa.vaj$$, ARRAY['work','everyday']),
($$aujourd'hui$$, $$today$$, $$Aujourd'hui, il fait beau.$$, 'A1', 'time', $$o.ʒuʁ.dɥi$$, ARRAY['time','everyday']),
($$demain$$, $$tomorrow$$, $$À demain !$$, 'A1', 'time', $$də.mɛ̃$$, ARRAY['time','everyday']),
-- A2
($$hier$$, $$yesterday$$, $$Hier, je suis allé au marché.$$, 'A2', 'time', $$jɛʁ$$, ARRAY['time','narration']),
($$le billet$$, $$ticket$$, $$J'ai acheté un billet de train.$$, 'A2', 'travel', $$bi.jɛ$$, ARRAY['travel']),
($$la gare$$, $$train station$$, $$La gare est près du centre-ville.$$, 'A2', 'travel', $$ɡaʁ$$, ARRAY['travel']),
($$le vêtement$$, $$piece of clothing$$, $$Ce magasin vend des vêtements pas chers.$$, 'A2', 'shopping', $$vɛt.mɑ̃$$, ARRAY['shopping']),
($$essayer$$, $$to try (on)$$, $$Je peux essayer cette veste ?$$, 'A2', 'verbs', $$e.sɛ.je$$, ARRAY['shopping','everyday']),
($$le médecin$$, $$doctor$$, $$Je dois voir le médecin demain.$$, 'A2', 'health', $$med.sɛ̃$$, ARRAY['health']),
($$avoir mal$$, $$to hurt / be in pain$$, $$J'ai mal à la tête.$$, 'A2', 'health', $$a.vwaʁ mal$$, ARRAY['health']),
($$la pluie$$, $$rain$$, $$La pluie va s'arrêter ce soir.$$, 'A2', 'weather', $$plɥi$$, ARRAY['weather']),
($$il fait beau$$, $$the weather is nice$$, $$Sortons, il fait beau !$$, 'A2', 'weather', $$il fɛ bo$$, ARRAY['weather','everyday']),
($$se réveiller$$, $$to wake up$$, $$Je me réveille à sept heures.$$, 'A2', 'verbs', $$sə ʁe.vɛ.je$$, ARRAY['routine']),
($$se souvenir$$, $$to remember$$, $$Je me souviens de mes vacances.$$, 'A2', 'verbs', $$sə suv.niʁ$$, ARRAY['narration']),
($$moins cher$$, $$cheaper$$, $$Ce restaurant est moins cher que l'autre.$$, 'A2', 'shopping', $$mwɛ̃ ʃɛʁ$$, ARRAY['shopping','comparison']),
($$la valise$$, $$suitcase$$, $$Ma valise est trop lourde.$$, 'A2', 'travel', $$va.liz$$, ARRAY['travel']),
($$réserver$$, $$to book, to reserve$$, $$Nous avons réservé une chambre d'hôtel.$$, 'A2', 'travel', $$ʁe.zɛʁ.ve$$, ARRAY['travel']),
($$l'ordonnance$$, $$prescription$$, $$Le médecin m'a donné une ordonnance.$$, 'A2', 'health', $$ɔʁ.dɔ.nɑ̃s$$, ARRAY['health']),
-- B1
($$l'avis$$, $$opinion$$, $$À mon avis, ce film est excellent.$$, 'B1', 'opinion', $$a.vi$$, ARRAY['debate','opinion']),
($$convaincre$$, $$to convince$$, $$Il m'a convaincu de venir.$$, 'B1', 'opinion', $$kɔ̃.vɛ̃kʁ$$, ARRAY['debate']),
($$l'entreprise$$, $$company$$, $$Elle travaille dans une grande entreprise.$$, 'B1', 'work', $$ɑ̃.tʁə.pʁiz$$, ARRAY['work']),
($$embaucher$$, $$to hire$$, $$L'entreprise embauche dix personnes cette année.$$, 'B1', 'work', $$ɑ̃.bo.ʃe$$, ARRAY['work']),
($$l'environnement$$, $$environment$$, $$Protéger l'environnement est urgent.$$, 'B1', 'society', $$ɑ̃.vi.ʁɔn.mɑ̃$$, ARRAY['society','debate']),
($$le réchauffement climatique$$, $$global warming$$, $$Le réchauffement climatique menace les côtes.$$, 'B1', 'society', $$ʁe.ʃof.mɑ̃ kli.ma.tik$$, ARRAY['society','news']),
($$les actualités$$, $$the news$$, $$Je regarde les actualités tous les soirs.$$, 'B1', 'media', $$ak.tɥa.li.te$$, ARRAY['media','news']),
($$le quotidien$$, $$daily newspaper / daily life$$, $$Ce quotidien publie une enquête intéressante.$$, 'B1', 'media', $$kɔ.ti.djɛ̃$$, ARRAY['media']),
($$il faut que$$, $$it is necessary that$$, $$Il faut que tu viennes demain.$$, 'B1', 'grammar', $$il fo kə$$, ARRAY['subjunctive']),
($$bien que$$, $$although$$, $$Bien qu'il pleuve, nous sortons.$$, 'B1', 'connectors', $$bjɛ̃ kə$$, ARRAY['subjunctive','connectors']),
($$le candidat$$, $$candidate, applicant$$, $$Le candidat a envoyé sa lettre de motivation.$$, 'B1', 'work', $$kɑ̃.di.da$$, ARRAY['work']),
($$la formation$$, $$training, education$$, $$Elle suit une formation en informatique.$$, 'B1', 'work', $$fɔʁ.ma.sjɔ̃$$, ARRAY['work','education']),
-- B2
($$néanmoins$$, $$nevertheless$$, $$Le projet est risqué ; néanmoins, il mérite d'être tenté.$$, 'B2', 'connectors', $$ne.ɑ̃.mwɛ̃$$, ARRAY['formal','writing']),
($$en revanche$$, $$on the other hand$$, $$Le service est lent ; en revanche, la cuisine est délicieuse.$$, 'B2', 'connectors', $$ɑ̃ ʁə.vɑ̃ʃ$$, ARRAY['formal','debate']),
($$la mondialisation$$, $$globalization$$, $$La mondialisation transforme l'économie.$$, 'B2', 'society', $$mɔ̃.dja.li.za.sjɔ̃$$, ARRAY['society','debate']),
($$l'enjeu$$, $$what is at stake, issue$$, $$L'enjeu de cette réforme est considérable.$$, 'B2', 'abstract', $$ɑ̃.ʒø$$, ARRAY['formal','debate']),
($$aborder$$, $$to tackle, to address (a topic)$$, $$L'article aborde la question du logement.$$, 'B2', 'abstract', $$a.bɔʁ.de$$, ARRAY['formal','writing']),
($$préconiser$$, $$to recommend, to advocate$$, $$Les experts préconisent plus de transports publics.$$, 'B2', 'formal', $$pʁe.kɔ.ni.ze$$, ARRAY['formal','news']),
($$le constat$$, $$observation, finding$$, $$Le constat est clair : il faut agir.$$, 'B2', 'formal', $$kɔ̃s.ta$$, ARRAY['formal','writing']),
($$la lecture$$, $$reading / interpretation$$, $$Sa lecture du roman est originale.$$, 'B2', 'culture', $$lɛk.tyʁ$$, ARRAY['culture','literature']),
($$quoique$$, $$although, even though$$, $$Quoique fatigué, il a terminé son travail.$$, 'B2', 'connectors', $$kwa.kə$$, ARRAY['subjunctive','formal']),
($$le pouvoir d'achat$$, $$purchasing power$$, $$Le pouvoir d'achat des ménages baisse.$$, 'B2', 'economy', $$pu.vwaʁ da.ʃa$$, ARRAY['economy','news']),
-- C1
($$en l'occurrence$$, $$in this case, as it happens$$, $$Il faut un expert ; en l'occurrence, un juriste.$$, 'C1', 'formal', $$ɑ̃ lɔ.ky.ʁɑ̃s$$, ARRAY['formal','soutenu']),
($$la problématique$$, $$central question, issue$$, $$Votre essai doit poser une problématique claire.$$, 'C1', 'academic', $$pʁɔ.ble.ma.tik$$, ARRAY['academic','writing']),
($$étayer$$, $$to support (an argument)$$, $$Étayez votre thèse avec des exemples précis.$$, 'C1', 'academic', $$e.tɛ.je$$, ARRAY['academic','writing']),
($$mettre en exergue$$, $$to highlight, to underscore$$, $$L'auteur met en exergue les contradictions du système.$$, 'C1', 'formal', $$mɛtʁ ɑ̃.n‿ɛɡ.zɛʁɡ$$, ARRAY['formal','writing']),
($$avoir le cafard$$, $$to feel down (idiom)$$, $$Depuis son départ, elle a le cafard.$$, 'C1', 'idioms', $$a.vwaʁ lə ka.faʁ$$, ARRAY['idioms','familiar']),
($$tourner autour du pot$$, $$to beat around the bush (idiom)$$, $$Arrête de tourner autour du pot et dis la vérité !$$, 'C1', 'idioms', $$tuʁ.ne o.tuʁ dy po$$, ARRAY['idioms','familiar']),
($$le fil conducteur$$, $$common thread$$, $$Le fil conducteur du film est la mémoire.$$, 'C1', 'culture', $$fil kɔ̃.dyk.tœʁ$$, ARRAY['culture','analysis']),
($$s'inscrire dans$$, $$to be part of, fit into (a context)$$, $$Cette loi s'inscrit dans une politique plus large.$$, 'C1', 'formal', $$sɛ̃s.kʁiʁ dɑ̃$$, ARRAY['formal','academic']),
-- C2
($$l'ambivalence$$, $$ambivalence$$, $$L'ambivalence du personnage fait la richesse du roman.$$, 'C2', 'abstract', $$ɑ̃.bi.va.lɑ̃s$$, ARRAY['literature','analysis']),
($$en filigrane$$, $$implicitly, beneath the surface$$, $$La critique sociale apparaît en filigrane du récit.$$, 'C2', 'formal', $$ɑ̃ fi.li.ɡʁan$$, ARRAY['literature','soutenu']),
($$l'euphémisme$$, $$euphemism$$, $$« Disparu » est un euphémisme pour « mort ».$$, 'C2', 'rhetoric', $$ø.fe.mism$$, ARRAY['rhetoric','analysis']),
($$la connivence$$, $$complicity, tacit understanding$$, $$Un sourire de connivence les unissait.$$, 'C2', 'abstract', $$kɔ.ni.vɑ̃s$$, ARRAY['literature','soutenu']),
($$jurisprudence$$, $$case law$$, $$La jurisprudence de la Cour a évolué sur ce point.$$, 'C2', 'law', $$ʒy.ʁis.pʁy.dɑ̃s$$, ARRAY['law','specialized']),
($$le calembour$$, $$pun$$, $$Ce titre repose sur un calembour intraduisible.$$, 'C2', 'humor', $$ka.lɑ̃.buʁ$$, ARRAY['humor','wordplay']),
($$peaufiner$$, $$to polish, to fine-tune$$, $$Il peaufine son discours jusqu'à la dernière minute.$$, 'C2', 'formal', $$po.fi.ne$$, ARRAY['writing','soutenu']),
($$l'ironie mordante$$, $$biting irony$$, $$L'ironie mordante de Voltaire traverse tout le conte.$$, 'C2', 'rhetoric', $$i.ʁɔ.ni mɔʁ.dɑ̃t$$, ARRAY['rhetoric','literature']);

-- 4. Grammar rules -----------------------------------------------------------

INSERT INTO public.grammar_rules (title, description, examples, level, category) VALUES
($$Definite and indefinite articles$$, $$French nouns are masculine or feminine. Use le/la/les for specific nouns and un/une/des for unspecific ones. Le and la become l' before a vowel.$$, ARRAY[$$le livre → the book$$, $$la table → the table$$, $$l'ami → the friend$$, $$une idée → an idea$$], 'A1', 'articles'),
($$Present tense of être and avoir$$, $$Être (to be) and avoir (to have) are irregular and must be memorized; they also serve as auxiliaries for compound tenses.$$, ARRAY[$$je suis, tu es, il est, nous sommes, vous êtes, ils sont$$, $$j'ai, tu as, il a, nous avons, vous avez, ils ont$$], 'A1', 'conjugation'),
($$Regular -er verbs$$, $$Remove -er and add -e, -es, -e, -ons, -ez, -ent. About 90% of French verbs follow this pattern.$$, ARRAY[$$parler : je parle, nous parlons$$, $$aimer : tu aimes, ils aiment$$], 'A1', 'conjugation'),
($$Negation with ne... pas$$, $$Wrap the conjugated verb with ne and pas. Ne becomes n' before a vowel.$$, ARRAY[$$Je ne parle pas anglais.$$, $$Elle n'aime pas le café.$$], 'A1', 'negation'),
($$Question formation$$, $$Ask questions with intonation, est-ce que, or inversion. Question words: qui, que, où, quand, pourquoi, comment.$$, ARRAY[$$Tu viens ? / Est-ce que tu viens ? / Viens-tu ?$$, $$Où habites-tu ?$$], 'A1', 'questions'),
($$Possessive adjectives$$, $$Mon/ma/mes, ton/ta/tes, son/sa/ses agree with the noun possessed, not the possessor.$$, ARRAY[$$mon frère, ma sœur, mes parents$$, $$sa voiture (his OR her car)$$], 'A1', 'adjectives'),
($$Passé composé with avoir$$, $$Most verbs form the past with avoir + past participle. Participles: -er → -é, -ir → -i, -re → -u.$$, ARRAY[$$J'ai mangé une pomme.$$, $$Nous avons fini le travail.$$, $$Elle a vendu sa maison.$$], 'A2', 'past-tenses'),
($$Passé composé with être$$, $$Movement/state-change verbs (aller, venir, partir...) and all reflexives use être; the participle agrees with the subject.$$, ARRAY[$$Elle est allée à Paris.$$, $$Ils sont partis tôt.$$, $$Nous nous sommes levés à huit heures.$$], 'A2', 'past-tenses'),
($$L'imparfait$$, $$Describes past habits, descriptions and ongoing actions. Stem = nous-form minus -ons, plus -ais, -ais, -ait, -ions, -iez, -aient.$$, ARRAY[$$Quand j'étais petit, je jouais au foot.$$, $$Il faisait beau ce jour-là.$$], 'A2', 'past-tenses'),
($$Futur proche and futur simple$$, $$Futur proche = aller + infinitive (immediate plans). Futur simple = infinitive + -ai, -as, -a, -ons, -ez, -ont (predictions, promises).$$, ARRAY[$$Je vais partir demain.$$, $$Nous voyagerons en été.$$], 'A2', 'future'),
($$Direct and indirect object pronouns$$, $$COD: me, te, le, la, nous, vous, les. COI: me, te, lui, nous, vous, leur. They precede the conjugated verb.$$, ARRAY[$$Je le vois. (I see him)$$, $$Je lui parle. (I speak to him/her)$$], 'A2', 'pronouns'),
($$Comparatives and superlatives$$, $$plus/moins/aussi + adjective + que; superlative adds le/la/les. Bon → meilleur; bien → mieux.$$, ARRAY[$$Paul est plus grand que Marie.$$, $$C'est le meilleur restaurant de la ville.$$], 'A2', 'comparison'),
($$Le subjonctif présent$$, $$Used after expressions of necessity, will, emotion and doubt (il faut que, je veux que, bien que). Stem from ils-form + -e, -es, -e, -ions, -iez, -ent.$$, ARRAY[$$Il faut que tu fasses tes devoirs.$$, $$Je suis content que vous soyez là.$$], 'B1', 'subjunctive'),
($$Relative pronouns qui, que, dont, où$$, $$Qui = subject, que = object, dont = of which/whose, où = where/when.$$, ARRAY[$$L'homme qui parle est mon voisin.$$, $$Le livre que je lis est passionnant.$$, $$Le film dont tu parles est sorti hier.$$], 'B1', 'pronouns'),
($$The conditional$$, $$Future stem + imparfait endings. Expresses politeness, wishes and hypotheses.$$, ARRAY[$$Je voudrais un café.$$, $$Si j'avais le temps, je voyagerais.$$], 'B1', 'conditional'),
($$Passé composé vs imparfait$$, $$Passé composé = completed events advancing the story; imparfait = background, description, habit.$$, ARRAY[$$Il pleuvait quand je suis sorti.$$, $$Elle lisait pendant que je cuisinais.$$], 'B1', 'past-tenses'),
($$Reported speech$$, $$Shift tenses when reporting: présent → imparfait, passé composé → plus-que-parfait, futur → conditionnel.$$, ARRAY[$$« Je viendrai » → Il a dit qu'il viendrait.$$, $$« J'ai fini » → Elle a dit qu'elle avait fini.$$], 'B1', 'syntax'),
($$Y and en$$, $$Y replaces à + place/thing; en replaces de + thing/quantity.$$, ARRAY[$$J'y vais demain.$$, $$Des pommes ? J'en achète trois.$$], 'B1', 'pronouns'),
($$Subjunctive vs indicative$$, $$Indicative after certainty (je pense que + affirmative); subjunctive after doubt, denial, emotion, and conjunctions like bien que, pour que, avant que.$$, ARRAY[$$Je pense qu'il vient.$$, $$Je ne pense pas qu'il vienne.$$, $$Bien qu'il soit tard, restons.$$], 'B2', 'subjunctive'),
($$The passive voice$$, $$Être + past participle (agreeing with subject); agent introduced by par. Formal French often prefers on or nominalization.$$, ARRAY[$$La loi a été votée par le Parlement.$$, $$On a voté la loi.$$], 'B2', 'syntax'),
($$Si clauses (hypotheses)$$, $$Si + présent → futur; si + imparfait → conditionnel présent; si + plus-que-parfait → conditionnel passé.$$, ARRAY[$$Si tu viens, nous sortirons.$$, $$Si j'étais riche, je voyagerais.$$, $$Si j'avais su, je serais venu.$$], 'B2', 'conditional'),
($$Discourse connectors$$, $$Structure formal speech and writing: d'abord, ensuite, en outre, cependant, en revanche, par conséquent, en somme.$$, ARRAY[$$Cependant, les résultats restent fragiles.$$, $$Par conséquent, il faut agir vite.$$], 'B2', 'connectors'),
($$Nominalization$$, $$Formal French turns verbs into nouns: développer → le développement. Common in press and academic style.$$, ARRAY[$$construire → la construction$$, $$La hausse des prix inquiète les ménages.$$], 'B2', 'style'),
($$Concession and opposition$$, $$Bien que/quoique + subjunctive; malgré + noun; pourtant, néanmoins, or, tandis que for contrast.$$, ARRAY[$$Bien qu'il pleuve, nous sortons.$$, $$Malgré la pluie, nous sortons.$$, $$Il est riche, pourtant il vit simplement.$$], 'B2', 'connectors'),
($$Le passé simple$$, $$Literary past tense replacing the passé composé in written narration. Recognize -a, -it, -ut, -int forms.$$, ARRAY[$$Il ouvrit la porte et sortit.$$, $$Elle fut surprise par sa réponse.$$], 'C1', 'past-tenses'),
($$Advanced pronoun combinations$$, $$Order of multiple pronouns: me/te/se/nous/vous before le/la/les before lui/leur before y before en.$$, ARRAY[$$Je le lui ai donné.$$, $$Il m'en a parlé.$$, $$Ne la leur montre pas !$$], 'C1', 'pronouns'),
($$The subjunctive past$$, $$Subjonctif passé (que j'aie fait) expresses completed actions in subjunctive contexts; imperfect subjunctive survives in literature.$$, ARRAY[$$Je suis ravi que tu aies réussi.$$, $$Il craignait qu'elle ne fût partie. (literary)$$], 'C1', 'subjunctive'),
($$Mise en relief (emphasis)$$, $$Highlight elements with c'est... qui/que, ce qui... c'est, and dislocation.$$, ARRAY[$$C'est lui qui a raison.$$, $$Ce qui compte, c'est la santé.$$, $$Ce livre, je l'adore.$$], 'C1', 'style'),
($$Register shifting$$, $$Choose vocabulary and syntax by register: soutenu (nous interrogeâmes), courant (nous avons demandé), familier (on a demandé).$$, ARRAY[$$se restaurer (soutenu) / manger (courant) / bouffer (familier)$$], 'C1', 'style'),
($$Literary inversion and style$$, $$Mastery-level French uses stylistic inversion, absolute constructions and rhythm for effect.$$, ARRAY[$$Peut-être viendra-t-il demain.$$, $$À peine était-il arrivé que le téléphone sonna.$$], 'C2', 'style'),
($$Ne explétif$$, $$A non-negative ne appearing after avant que, à moins que, craindre que in careful French.$$, ARRAY[$$Je crains qu'il ne soit trop tard.$$, $$Partons avant qu'il ne pleuve.$$], 'C2', 'syntax'),
($$Subtle mood and tense nuances$$, $$Contrast conditionnel journalistique, futur antérieur of conjecture and other native-level nuances.$$, ARRAY[$$Le président aurait démissionné. (unconfirmed report)$$, $$Il aura encore oublié. (he must have forgotten)$$], 'C2', 'conjugation');

-- 5. Conversation templates --------------------------------------------------

INSERT INTO public.conversation_templates (title, description, system_prompt, initial_message, topics, level) VALUES
($$Au café$$, $$Order drinks and snacks in a Parisian café.$$, $$You are a friendly Parisian café waiter speaking with an A1 beginner. Use very simple French, short sentences, present tense only. If the learner struggles, offer the English translation in parentheses. Stay in the café scenario: greet, take orders, discuss prices, say goodbye.$$, $$Bonjour ! Bienvenue au Café du Coin. Vous désirez ? (Hello! Welcome. What would you like?)$$, ARRAY['food','everyday','politeness'], 'A1'),
($$Les présentations$$, $$Introduce yourself and ask simple questions about someone.$$, $$You are a friendly French student meeting an A1 beginner for the first time. Use very simple French: name, age, nationality, hobbies. One short question at a time. Gently correct big mistakes and give the English translation in parentheses when the learner seems lost.$$, $$Salut ! Je m'appelle Léa. Et toi, comment tu t'appelles ? (Hi! My name is Léa. What's your name?)$$, ARRAY['introductions','everyday'], 'A1'),
($$À la gare$$, $$Buy train tickets and ask about schedules.$$, $$You are an SNCF ticket agent speaking with an A2 learner. Use simple but natural French, présent and futur proche. Handle: destinations, times, prices, platforms. Ask one question at a time and rephrase instead of translating unless truly stuck.$$, $$Bonjour ! Vous voulez acheter un billet ? Pour quelle destination ?$$, ARRAY['travel','transport'], 'A2'),
($$Chez le médecin$$, $$Describe symptoms and understand a doctor's advice.$$, $$You are a kind French doctor with an A2 patient. Use simple French to ask about symptoms, give simple advice with il faut + infinitive. Keep sentences short and confirm understanding often.$$, $$Bonjour, asseyez-vous. Alors, qu'est-ce qui ne va pas aujourd'hui ?$$, ARRAY['health','everyday'], 'A2'),
($$Entretien d'embauche$$, $$Practice a job interview in French.$$, $$You are a French HR manager interviewing a B1 candidate. Ask about experience, strengths, motivation. Use natural professional French; follow up on answers. After every few exchanges, give one short tip on register or vocabulary in French.$$, $$Bonjour, merci d'être venu. Pour commencer, pouvez-vous vous présenter en quelques mots ?$$, ARRAY['work','formal'], 'B1'),
($$Débat : la vie en ville ou à la campagne$$, $$Defend a position in an informal debate.$$, $$You are a French friend who loves debating with a B1 learner. Defend the opposite of whatever the learner argues about city vs countryside life. Use opinion phrases (à mon avis, je trouve que) and ask them to justify. Keep it friendly and correct recurring errors briefly.$$, $$Alors, dis-moi : tu préfères la vie en ville ou à la campagne ? Moi, j'ai un avis très tranché !$$, ARRAY['debate','society'], 'B1'),
($$Réunion de travail$$, $$Participate in a professional meeting: propose, agree, object.$$, $$You are chairing a small French team meeting with a B2 participant. Discuss a project (choose one: office move, product launch, budget cuts). Push them to propose, concede and object using formal connectors. Speak naturally, no translations.$$, $$Bien, commençons. Comme vous le savez, nous devons décider du lancement du nouveau produit. Quel est votre point de vue ?$$, ARRAY['work','formal','debate'], 'B2'),
($$Discussion d'actualité$$, $$Analyze a news topic in depth.$$, $$You are a well-informed French journalist discussing current affairs with a B2 learner. Pick a societal topic (environment, technology, education), present nuanced viewpoints and challenge the learner's arguments. Use authentic press vocabulary and idioms; briefly explain rare terms in French.$$, $$Vous avez suivi l'actualité récemment ? Il y a un sujet qui fait débat en ce moment et j'aimerais votre avis.$$, ARRAY['news','society','debate'], 'B2'),
($$Défendre une thèse$$, $$Sustain an academic-style argument under challenge.$$, $$You are a demanding French professor holding a C1 oral examination. The learner must defend a position on a complex issue you choose. Interrupt with counterarguments, demand precision, and require formal register. Point out anglicisms and register slips as they occur.$$, $$Bien. Le sujet du jour : « Le progrès technique libère-t-il l'être humain ? » Je vous écoute — exposez votre thèse.$$, ARRAY['academic','debate','formal'], 'C1'),
($$Conversation entre amis natifs$$, $$Keep up with fast, idiomatic, informal French.$$, $$You are a native French friend chatting with a C1 learner. Speak exactly as natives do between friends: fast rhythm in writing, contractions (t'as, j'sais pas), slang and idioms. If the learner misses an idiom, rephrase it once in standard French and continue.$$, $$Salut ! Alors, quoi de neuf ? T'as passé un bon week-end ? Moi, il m'est arrivé un truc de dingue...$$, ARRAY['informal','idioms','everyday'], 'C1'),
($$Joute rhétorique$$, $$A no-holds-barred debate at native level.$$, $$You are a brilliant French debater sparring with a C2 learner. Choose a philosophical or societal motion and argue with rhetoric: irony, concession, rhetorical questions, literary references. Expect and reward the same in return; analyze their rhetoric between rounds.$$, $$Installons le décor : « La vérité est-elle toujours bonne à dire ? » Je soutiendrai que non — et je vous préviens, je ne vous épargnerai pas.$$, ARRAY['rhetoric','debate','academic'], 'C2'),
($$Analyse littéraire$$, $$Discuss a literary text like a French literature seminar.$$, $$You are a French literature professor in a C2 seminar. Discuss style, themes and interpretation of classic French works the learner knows (offer choices: Camus, Proust, Duras...). Demand precise literary vocabulary and nuanced analysis; model elegant academic French.$$, $$Bienvenue dans ce séminaire. Par quelle œuvre souhaitez-vous commencer ? L'Étranger de Camus se prête admirablement à l'analyse de l'absurde.$$, ARRAY['literature','academic','culture'], 'C2');

-- 6. Pronunciation exercises -------------------------------------------------

INSERT INTO public.pronunciation_exercises (text, translation, level, category) VALUES
($$Bonjour, je m'appelle Marie.$$, $$Hello, my name is Marie.$$, 'A1', 'basics'),
($$Un, deux, trois, quatre, cinq.$$, $$One, two, three, four, five.$$, 'A1', 'numbers'),
($$Le chat est sur la chaise.$$, $$The cat is on the chair.$$, 'A1', 'vowels'),
($$Tu as un très bon accent.$$, $$You have a very good accent.$$, 'A1', 'nasal-vowels'),
($$Je voudrais un café, s'il vous plaît.$$, $$I would like a coffee, please.$$, 'A1', 'basics'),
($$Nous allons au marché ce matin.$$, $$We are going to the market this morning.$$, 'A2', 'liaison'),
($$Il fait beau mais un peu froid.$$, $$The weather is nice but a little cold.$$, 'A2', 'vowels'),
($$Mon frère habite en Bretagne.$$, $$My brother lives in Brittany.$$, 'A2', 'nasal-vowels'),
($$Elle a acheté des oranges et des œufs.$$, $$She bought oranges and eggs.$$, 'A2', 'liaison'),
($$Hier soir, nous avons regardé un film.$$, $$Last night, we watched a movie.$$, 'A2', 'rhythm'),
($$Il faut que nous partions avant l'aube.$$, $$We must leave before dawn.$$, 'B1', 'rhythm'),
($$La grenouille rousse traverse le ruisseau.$$, $$The red frog crosses the stream.$$, 'B1', 'r-sound'),
($$Je me suis souvenu de son numéro de téléphone.$$, $$I remembered his phone number.$$, 'B1', 'u-sound'),
($$Les Français apprécient les longues discussions.$$, $$The French enjoy long discussions.$$, 'B1', 'nasal-vowels'),
($$Quoi qu'il en soit, nous y arriverons ensemble.$$, $$Be that as it may, we will get there together.$$, 'B1', 'rhythm'),
($$Un bon vin blanc accompagne bien ce plat.$$, $$A good white wine goes well with this dish.$$, 'B2', 'nasal-vowels'),
($$Ils s'inscrivirent aussitôt à l'université.$$, $$They immediately enrolled at the university.$$, 'B2', 'consonant-clusters'),
($$La bureaucratie européenne évolue lentement.$$, $$European bureaucracy evolves slowly.$$, 'B2', 'vowels'),
($$Néanmoins, l'hypothèse mérite d'être examinée.$$, $$Nevertheless, the hypothesis deserves examination.$$, 'B2', 'rhythm'),
($$Les enfants ont apporté leurs propres histoires.$$, $$The children brought their own stories.$$, 'B2', 'liaison'),
($$L'obscurité enveloppait insensiblement la ville.$$, $$Darkness imperceptibly enveloped the city.$$, 'C1', 'rhythm'),
($$Il eût fallu davantage de rigueur scientifique.$$, $$More scientific rigor would have been needed.$$, 'C1', 'literary'),
($$Ses scrupules l'empêchaient d'agir spontanément.$$, $$His scruples prevented him from acting spontaneously.$$, 'C1', 'consonant-clusters'),
($$L'inexorable écoulement du temps nous échappe.$$, $$The inexorable passage of time escapes us.$$, 'C1', 'vowels'),
($$Un heureux hasard réunit les deux chercheurs.$$, $$A happy coincidence brought the two researchers together.$$, 'C1', 'h-aspire'),
($$Les chuchotements s'évanouirent dans l'amphithéâtre.$$, $$The whispers faded away in the lecture hall.$$, 'C2', 'consonant-clusters'),
($$Serait-ce l'ultime paradoxe de la modernité ?$$, $$Could this be the ultimate paradox of modernity?$$, 'C2', 'intonation'),
($$L'archaïsme de cette tournure séduit les puristes.$$, $$The archaism of this phrasing delights purists.$$, 'C2', 'rhythm'),
($$Peut-être eût-il préféré qu'on l'oubliât.$$, $$Perhaps he would have preferred to be forgotten.$$, 'C2', 'literary'),
($$Les feuilles bruissaient sous un ciel d'une pureté saisissante.$$, $$The leaves rustled under a strikingly pure sky.$$, 'C2', 'rhythm');
